sonata_seo:
    encoding:         UTF-8
    page:
        metas:
            name:
                description:  Seb votre coach personnel. Coach sportif diplômé, expérimenté, passionné et bienveillant.
                robots:       index, follow

            property:
                            # Facebook application settings
                            #'fb:app_id':          XXXXXX
                            #'fb:admins':          admin1, admin2

                            # Open Graph information
                            # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                            'og:site_name': Paléolife
                            'og:description': Seb votre coach personnel. Coach sportif diplômé, expérimenté, passionné et bienveillant.
                            'og:title': Paléolife
                            'og:url':  https://www.paléolife-coaching.fr/
                            'og:type': website
                            'og:image': https://www.paléolife-coaching.fr/build/images/Logo.28577b1c.png

            http-equiv:
                'Content-Type': text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
                    'xmlns':              http://www.w3.org/1999/xhtml
                    'xmlns:og':           http://opengraphprotocol.org/schema/
