vich_uploader:
    db_driver: orm

    mappings:
        client_image:
            uri_prefix: /uploads/client
            upload_destination: '%kernel.project_dir%/public/uploads/client'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    
    metadata:
        type: attribute